.TH "ahtxx_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ahtxx_context_t \- AHTXX context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ahtxx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBahtxx_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AHTXX context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBahtxx_config_t\fP dev_config"
ahtxx device configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
ahtxx i2c device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
