.TH "ak8975_axes_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ak8975_axes_data_s \- AK8975 axes data registers (HX, HZ, HZ) structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ak8975\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbytes_to_int16_t\fP \fBx_axis\fP"
.br
.ti -1c
.RI "\fBbytes_to_int16_t\fP \fBy_axis\fP"
.br
.ti -1c
.RI "\fBbytes_to_int16_t\fP \fBz_axis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AK8975 axes data registers (HX, HZ, HZ) structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
