.TH "as3935_monitor_base_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
as3935_monitor_base_s \- AS3935 device event object structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <as3935\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBas3935_lightning_distances_t\fP \fBlightning_distance\fP"
.br
.ti -1c
.RI "uint32_t \fBlightning_energy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AS3935 device event object structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
