.TH "as3935_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
as3935_config_s \- I2C AS3935 device configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <as3935\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "bool \fBirq_io_enabled\fP"
.br
.ti -1c
.RI "uint32_t \fBirq_io_num\fP"
.br
.ti -1c
.RI "\fBas3935_analog_frontends_t\fP \fBanalog_frontend\fP"
.br
.ti -1c
.RI "\fBas3935_minimum_lightnings_t\fP \fBmin_lightning_strikes\fP"
.br
.ti -1c
.RI "bool \fBcalibrate_rco\fP"
.br
.ti -1c
.RI "bool \fBdisturber_detection_enabled\fP"
.br
.ti -1c
.RI "\fBas3935_noise_levels_t\fP \fBnoise_level_threshold\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2C AS3935 device configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBas3935_analog_frontends_t\fP analog_frontend"
as3935 indoor or outdoor exposure 
.SS "bool calibrate_rco"
as3935 rco is calibrated when true 
.SS "bool disturber_detection_enabled"
as3935 disturber detection is enabled when true 
.SS "uint16_t i2c_address"
as3935 i2c device address 
.SS "uint32_t i2c_clock_speed"
as3935 i2c device scl clock speed in hz 
.SS "bool irq_io_enabled"
as3935 interrupt pin enabled when true 
.SS "uint32_t irq_io_num"
as3935 pin number for mcu interrupt 
.SS "\fBas3935_minimum_lightnings_t\fP min_lightning_strikes"
as3935 minimum number of lightning strikes before an event is raised 
.SS "\fBas3935_noise_levels_t\fP noise_level_threshold"
as3935 noise level threshold 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
