.TH "as3935_monitor_context_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
as3935_monitor_context_s \- esp AS3935 device state machine structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <as3935\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBirq_io_num\fP"
.br
.ti -1c
.RI "\fBas3935_monitor_base_t\fP \fBbase\fP"
.br
.ti -1c
.RI "esp_event_loop_handle_t \fBevent_loop_handle\fP"
.br
.ti -1c
.RI "QueueHandle_t \fBevent_queue_handle\fP"
.br
.ti -1c
.RI "TaskHandle_t \fBtask_monitor_handle\fP"
.br
.ti -1c
.RI "\fBas3935_handle_t\fP \fBas3935_handle\fP"
.br
.ti -1c
.RI "SemaphoreHandle_t \fBi2c_mutex_handle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
esp AS3935 device state machine structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBas3935_handle_t\fP as3935_handle"
as3935 handle 
.SS "\fBas3935_monitor_base_t\fP base"
as3935 device parent class 
.SS "esp_event_loop_handle_t event_loop_handle"
as3935 event loop handle 
.SS "QueueHandle_t event_queue_handle"
as3935 event queue handle 
.SS "SemaphoreHandle_t i2c_mutex_handle"
I2C master bus mutex handle 
.SS "uint32_t irq_io_num"
as3935 interrupt pin to mcu 
.SS "TaskHandle_t task_monitor_handle"
as3935 task monitor handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
