.TH "as7341_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
as7341_config_s \- AS7341 configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <as7341\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "uint8_t \fBatime\fP"
.br
.ti -1c
.RI "uint16_t \fBastep\fP"
.br
.ti -1c
.RI "\fBas7341_spectral_gains_t\fP \fBspectral_gain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AS7341 configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t i2c_address"
as7341 i2c device address 
.SS "uint32_t i2c_clock_speed"
as7341 i2c device scl clock speed in hz 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
