.TH "as7341_channels_spectral_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
as7341_channels_spectral_data_s \- AS7341 channels spectral data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <as7341\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBf1\fP"
.br
.ti -1c
.RI "uint16_t \fBf2\fP"
.br
.ti -1c
.RI "uint16_t \fBf3\fP"
.br
.ti -1c
.RI "uint16_t \fBf4\fP"
.br
.ti -1c
.RI "uint16_t \fBf5\fP"
.br
.ti -1c
.RI "uint16_t \fBf6\fP"
.br
.ti -1c
.RI "uint16_t \fBf7\fP"
.br
.ti -1c
.RI "uint16_t \fBf8\fP"
.br
.ti -1c
.RI "uint16_t \fBclear\fP"
.br
.ti -1c
.RI "uint16_t \fBnir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AS7341 channels spectral data structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t f1"
405 to 425 nm 
.SS "uint16_t f2"
435 to 455 nm 
.SS "uint16_t f3"
470 to 490 nm 
.SS "uint16_t f4"
505 to 525 nm 
.SS "uint16_t f5"
545 to 565 nm 
.SS "uint16_t f6"
580 to 600 nm 
.SS "uint16_t f7"
620 to 640 nm 
.SS "uint16_t f8"
670 to 690 nm 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
