.TH "as7341_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
as7341_context_t \- AS7341 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <as7341\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBas7341_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "uint8_t \fBpart_id\fP"
.br
.ti -1c
.RI "uint8_t \fBrevision_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AS7341 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBas7341_config_t\fP dev_config"
as7341 device configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
as7341 i2c device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
