.TH "as7341_channels_basic_counts_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
as7341_channels_basic_counts_data_s \- AS7341 channels basic counts data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <as7341\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBf1\fP"
.br
.ti -1c
.RI "float \fBf2\fP"
.br
.ti -1c
.RI "float \fBf3\fP"
.br
.ti -1c
.RI "float \fBf4\fP"
.br
.ti -1c
.RI "float \fBf5\fP"
.br
.ti -1c
.RI "float \fBf6\fP"
.br
.ti -1c
.RI "float \fBf7\fP"
.br
.ti -1c
.RI "float \fBf8\fP"
.br
.ti -1c
.RI "float \fBclear\fP"
.br
.ti -1c
.RI "float \fBnir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AS7341 channels basic counts data structure\&. 
.SH "Field Documentation"
.PP 
.SS "float f1"
405 to 425 nm 
.SS "float f2"
435 to 455 nm 
.SS "float f3"
470 to 490 nm 
.SS "float f4"
505 to 525 nm 
.SS "float f5"
545 to 565 nm 
.SS "float f6"
580 to 600 nm 
.SS "float f7"
620 to 640 nm 
.SS "float f8"
670 to 690 nm 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
