.TH "bh1750_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bh1750_config_s \- BH1750 device configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bh1750\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "\fBbh1750_measurement_modes_t\fP \fBmode\fP"
.br
.ti -1c
.RI "uint8_t \fBtimespan\fP"
.br
.ti -1c
.RI "bool \fBset_timespan\fP"
.br
.ti -1c
.RI "bool \fBpower_enabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BH1750 device configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t i2c_address"
bh1750 i2c device address 
.SS "uint32_t i2c_clock_speed"
bh1750 i2c device scl clock speed in hz 
.SS "\fBbh1750_measurement_modes_t\fP mode"
bh1750 measurement mode 
.SS "bool power_enabled"
bh1750 powered up at initialization 
.SS "bool set_timespan"
set bh1750 measurement timespan when true 
.SS "uint8_t timespan"
bh1750 measurement time duration 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
