.TH "bme680_cal_factors_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme680_cal_factors_s \- BME680 calibration factors structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bme680\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBpar_T1\fP"
.br
.ti -1c
.RI "int16_t \fBpar_T2\fP"
.br
.ti -1c
.RI "int8_t \fBpar_T3\fP"
.br
.ti -1c
.RI "float \fBtemperature_fine\fP"
.br
.ti -1c
.RI "uint16_t \fBpar_H1\fP"
.br
.ti -1c
.RI "uint16_t \fBpar_H2\fP"
.br
.ti -1c
.RI "int8_t \fBpar_H3\fP"
.br
.ti -1c
.RI "int8_t \fBpar_H4\fP"
.br
.ti -1c
.RI "int8_t \fBpar_H5\fP"
.br
.ti -1c
.RI "uint8_t \fBpar_H6\fP"
.br
.ti -1c
.RI "int8_t \fBpar_H7\fP"
.br
.ti -1c
.RI "uint16_t \fBpar_P1\fP"
.br
.ti -1c
.RI "int16_t \fBpar_P2\fP"
.br
.ti -1c
.RI "int8_t \fBpar_P3\fP"
.br
.ti -1c
.RI "int16_t \fBpar_P4\fP"
.br
.ti -1c
.RI "int16_t \fBpar_P5\fP"
.br
.ti -1c
.RI "int8_t \fBpar_P6\fP"
.br
.ti -1c
.RI "int8_t \fBpar_P7\fP"
.br
.ti -1c
.RI "int16_t \fBpar_P8\fP"
.br
.ti -1c
.RI "int16_t \fBpar_P9\fP"
.br
.ti -1c
.RI "uint8_t \fBpar_P10\fP"
.br
.ti -1c
.RI "int8_t \fBpar_G1\fP"
.br
.ti -1c
.RI "int16_t \fBpar_G2\fP"
.br
.ti -1c
.RI "int8_t \fBpar_G3\fP"
.br
.ti -1c
.RI "uint8_t \fBres_heat_range\fP"
.br
.ti -1c
.RI "int8_t \fBres_heat_val\fP"
.br
.ti -1c
.RI "int8_t \fBrange_switching_error\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BME680 calibration factors structure definition\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
