.TH "bme680_adc_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme680_adc_data_s \- BME680 ADC data structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bme680\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtemperature\fP"
.br
.ti -1c
.RI "uint16_t \fBhumidity\fP"
.br
.ti -1c
.RI "uint32_t \fBpressure\fP"
.br
.ti -1c
.RI "uint16_t \fBgas\fP"
.br
.ti -1c
.RI "bool \fBgas_valid\fP"
.br
.ti -1c
.RI "uint8_t \fBgas_range\fP"
.br
.ti -1c
.RI "uint8_t \fBgas_index\fP"
.br
.ti -1c
.RI "bool \fBheater_stable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BME680 ADC data structure definition\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
