.TH "bme680_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme680_config_s \- BME680 configuration structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bme680\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "\fBbme680_power_modes_t\fP \fBpower_mode\fP"
.br
.ti -1c
.RI "\fBbme680_iir_filters_t\fP \fBiir_filter\fP"
.br
.ti -1c
.RI "\fBbme680_pressure_oversampling_t\fP \fBpressure_oversampling\fP"
.br
.ti -1c
.RI "\fBbme680_temperature_oversampling_t\fP \fBtemperature_oversampling\fP"
.br
.ti -1c
.RI "\fBbme680_humidity_oversampling_t\fP \fBhumidity_oversampling\fP"
.br
.ti -1c
.RI "bool \fBgas_enabled\fP"
.br
.ti -1c
.RI "uint16_t \fBheater_temperature\fP"
.br
.ti -1c
.RI "uint16_t \fBheater_duration\fP"
.br
.ti -1c
.RI "uint16_t \fBheater_temperature_profile\fP [BME680_HEATER_PROFILE_SIZE]"
.br
.ti -1c
.RI "uint16_t \fBheater_duration_profile\fP [BME680_HEATER_PROFILE_SIZE]"
.br
.ti -1c
.RI "uint8_t \fBheater_profile_size\fP"
.br
.ti -1c
.RI "uint16_t \fBheater_shared_duration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BME680 configuration structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "bool gas_enabled"
bme680 gas measurements enabled when true 
.SS "uint16_t heater_duration"
bme680 heating duration for forced mode in milliseconds 
.SS "uint16_t heater_duration_profile[BME680_HEATER_PROFILE_SIZE]"
bme680 heating duration profile in milliseconds 
.SS "uint8_t heater_profile_size"
bme680 size of the heating profile 
.SS "uint16_t heater_shared_duration"
bme680 heating duration for parallel mode in milliseconds 
.SS "uint16_t heater_temperature"
bme680 heater temperature for forced mode in degrees celsius 
.SS "uint16_t heater_temperature_profile[BME680_HEATER_PROFILE_SIZE]"
bme680 heater temperature profile in degrees celsius 
.SS "uint16_t i2c_address"
bme680 i2c device address 
.SS "uint32_t i2c_clock_speed"
bme680 i2c device scl clock speed 
.SS "\fBbme680_power_modes_t\fP power_mode"
bme680 power mode 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
