.TH "bme680_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bme680_context_t \- BME680 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bme680\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbme680_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "\fBbme680_cal_factors_t\fP * \fBdev_cal_factors\fP"
.br
.ti -1c
.RI "uint8_t \fBchip_id\fP"
.br
.ti -1c
.RI "uint16_t \fBambient_temperature\fP"
.br
.ti -1c
.RI "uint8_t \fBvariant_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BME680 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t chip_id"
bme680 chip identification register 
.SS "\fBbme680_cal_factors_t\fP* dev_cal_factors"
bme680 device calibration factors 
.SS "\fBbme680_config_t\fP dev_config"
bme680 device configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
bme680 I2C device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
