.TH "bmp280_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmp280_config_s \- BMP280 configuration structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bmp280\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "\fBbmp280_power_modes_t\fP \fBpower_mode\fP"
.br
.ti -1c
.RI "\fBbmp280_iir_filters_t\fP \fBiir_filter\fP"
.br
.ti -1c
.RI "\fBbmp280_pressure_oversampling_t\fP \fBpressure_oversampling\fP"
.br
.ti -1c
.RI "\fBbmp280_temperature_oversampling_t\fP \fBtemperature_oversampling\fP"
.br
.ti -1c
.RI "\fBbmp280_standby_times_t\fP \fBstandby_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BMP280 configuration structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t i2c_address"
bmp280 i2c device address 
.SS "uint32_t i2c_clock_speed"
bmp280 i2c device scl clock speed 
.SS "\fBbmp280_iir_filters_t\fP iir_filter"
bmp280 IIR filter setting 
.SS "\fBbmp280_power_modes_t\fP power_mode"
bmp280 power mode setting 
.SS "\fBbmp280_pressure_oversampling_t\fP pressure_oversampling"
bmp280 pressure oversampling setting 
.SS "\fBbmp280_standby_times_t\fP standby_time"
bmp280 stand-by time setting 
.SS "\fBbmp280_temperature_oversampling_t\fP temperature_oversampling"
bmp280 temperature oversampling setting 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
