.TH "bmp280_cal_factors_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmp280_cal_factors_s \- BMP280 temperature and pressure calibration factors structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bmp280\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBdig_T1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_T2\fP"
.br
.ti -1c
.RI "int16_t \fBdig_T3\fP"
.br
.ti -1c
.RI "uint16_t \fBdig_P1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P2\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P3\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P4\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P5\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P6\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P7\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P8\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P9\fP"
.br
.ti -1c
.RI "int32_t \fBt_fine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BMP280 temperature and pressure calibration factors structure definition\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
