.TH "bmp390_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmp390_config_s \- BMP390 configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bmp390\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "\fBbmp390_iir_filters_t\fP \fBiir_filter\fP"
.br
.ti -1c
.RI "\fBbmp390_pressure_oversampling_t\fP \fBpressure_oversampling\fP"
.br
.ti -1c
.RI "\fBbmp390_temperature_oversampling_t\fP \fBtemperature_oversampling\fP"
.br
.ti -1c
.RI "\fBbmp390_output_data_rates_t\fP \fBoutput_data_rate\fP"
.br
.ti -1c
.RI "\fBbmp390_power_modes_t\fP \fBpower_mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BMP390 configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t i2c_address"
bmp390 i2c device address 
.SS "uint32_t i2c_clock_speed"
bmp390 i2c device scl clock speed 
.SS "\fBbmp390_iir_filters_t\fP iir_filter"
bmp390 IIR filter setting 
.SS "\fBbmp390_output_data_rates_t\fP output_data_rate"
bmp390 output data rate setting 
.SS "\fBbmp390_power_modes_t\fP power_mode"
bmp390 power mode setting 
.SS "\fBbmp390_pressure_oversampling_t\fP pressure_oversampling"
bmp390 pressure oversampling setting 
.SS "\fBbmp390_temperature_oversampling_t\fP temperature_oversampling"
bmp390 temperature oversampling setting 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
