.TH "bmp390_conv_cal_factors_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bmp390_conv_cal_factors_s \- BMP390 temperature and pressure converted calibration factors structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bmp390\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBPAR_T1\fP"
.br
.ti -1c
.RI "double \fBPAR_T2\fP"
.br
.ti -1c
.RI "double \fBPAR_T3\fP"
.br
.ti -1c
.RI "double \fBPAR_P1\fP"
.br
.ti -1c
.RI "double \fBPAR_P2\fP"
.br
.ti -1c
.RI "double \fBPAR_P3\fP"
.br
.ti -1c
.RI "double \fBPAR_P4\fP"
.br
.ti -1c
.RI "double \fBPAR_P5\fP"
.br
.ti -1c
.RI "double \fBPAR_P6\fP"
.br
.ti -1c
.RI "double \fBPAR_P7\fP"
.br
.ti -1c
.RI "double \fBPAR_P8\fP"
.br
.ti -1c
.RI "double \fBPAR_P9\fP"
.br
.ti -1c
.RI "double \fBPAR_P10\fP"
.br
.ti -1c
.RI "double \fBPAR_P11\fP"
.br
.ti -1c
.RI "double \fBt_lin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BMP390 temperature and pressure converted calibration factors structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
