.TH "components/peripherals Directory Reference" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBadc\fP"
.br
.ti -1c
.RI "directory \fBi2c\fP"
.br
.ti -1c
.RI "directory \fBowb\fP"
.br
.ti -1c
.RI "directory \fBspi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP

.PP
The ESP-IDF peripheral components accommodate ADC, I2C, OWB, and SPI device interfacing supported by various device manufacturers\&. Components are developed when needed for product development and/or prototyping purposes, and shared with the ESP32 community for ESP-IDF developers\&. Custom component development is available upon request, please contact me directly, and I would be happy to discuss the details of your component needs\&. If any problems arise please feel free to log an issue and if you would to contribute please contact me\&.

.PP
ESP-IDF peripheral components that are flagged as completed work but they are undergoing refactoring and updates to satisfy ESP-IDF component packaging requirements (https://docs.espressif.com/projects/idf-component-manager/en/latest/guides/packaging_components.html) and PlatformIO library packaging requirements (https://docs.platformio.org/en/latest/librarymanager/index.html)\&.
.SH "ADC"
.PP
ESP-IDF component development status:

.PP
.IP "\(bu" 2
Roithner LaserTechnik GUVA-S12SD: component is synchronized with the esp-idf component registry and platform io library registry\&.
.PP
.SH "I2C"
.PP
ESP-IDF component development status:

.PP
.IP "\(bu" 2
ASAIR AHTXX: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
AKM AK8975: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
AMS AS3935: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
OSRAM AS7341: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
ROHM BH1750FVI: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Bosch BME680: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Bosch BMP280: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Bosch BMP390: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
ScioSense CCS811: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
ScioSense ENS160: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Texas Instruments HDC1080: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Honeywell HMC5883L: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Texas Instruments INA226: to be synchronized\&.\&.\&.
.IP "\(bu" 2
Lite-On LTR390UV: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Maxim-Integrated MAX30105: component development is work in progress (WIP)\&.
.IP "\(bu" 2
Melexis MLX90614: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Memsic MMC56X3: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
InvenSense MPU6050: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Sensirion SGP4X: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Sensirion SHT4X: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Generic SSD1306: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Infineon TLV493D: component development is work in progress (WIP)\&.
.IP "\(bu" 2
Vishay VEML6040: component is synchronized with the esp-idf component registry and platform io library registry\&.
.IP "\(bu" 2
Vishay VEML7700: component is synchronized with the esp-idf component registry and platform io library registry\&.
.PP
.SH "OWB"
.PP
ESP-IDF component development status:

.PP
.IP "\(bu" 2
Maxim-Integrated DS18B20: component is synchronized with the esp-idf component registry and platform io library registry\&.
.PP
.SH "SPI"
.PP
ESP-IDF component development status:

.PP
.IP "\(bu" 2
Analog Devices MAX31865: component development is work in progress (WIP)\&.
.PP

.PP
Copyright (c) 2024 Eric Gionet (gionet.c.eric@gmail.com) 
