.TH "components/peripherals/owb/onewire_bus Directory Reference" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/owb/onewire_bus Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBinterface\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fR\fP

.PP
This directory contains an implementation for Dallas 1-Wire bus by different peripherals\&. Currently only RMT is supported as the backend\&.

.PP
https://github.com/espressif/idf-extra-components/tree/master/onewire_bus 
