.TH "components/utilities Directory Reference" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/utilities Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBesp_kalman_motion\fP"
.br
.ti -1c
.RI "directory \fBesp_math3d\fP"
.br
.ti -1c
.RI "directory \fBesp_pressure_tendency\fP"
.br
.ti -1c
.RI "directory \fBesp_scalar_trend\fP"
.br
.ti -1c
.RI "directory \fBesp_type_utils\fP"
.br
.ti -1c
.RI "directory \fBesp_uuid\fP"
.br
.ti -1c
.RI "directory \fBesp_wx_utils\fP"
.br
.ti -1c
.RI "directory \fBsensirion_gas_index_algorithm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP

.PP
The \fRutilities\fP components folder holds generic libraries for data processing that are commonly used in conjunction with device driver components\&. These components are still work in progress and haven't been tested thoroughly at this time\&. Feel free to log issues if you give any of them a try and notice abnormal results\&.

.PP
Copyright (c) 2024 Eric Gionet (gionet.c.eric@gmail.com) 
