.TH "components/peripherals/i2c Directory Reference" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/i2c Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBesp_ahtxx\fP"
.br
.ti -1c
.RI "directory \fBesp_ak8975\fP"
.br
.ti -1c
.RI "directory \fBesp_as3935\fP"
.br
.ti -1c
.RI "directory \fBesp_as7341\fP"
.br
.ti -1c
.RI "directory \fBesp_bh1750\fP"
.br
.ti -1c
.RI "directory \fBesp_bme680\fP"
.br
.ti -1c
.RI "directory \fBesp_bmp280\fP"
.br
.ti -1c
.RI "directory \fBesp_bmp390\fP"
.br
.ti -1c
.RI "directory \fBesp_ccs811\fP"
.br
.ti -1c
.RI "directory \fBesp_ens160\fP"
.br
.ti -1c
.RI "directory \fBesp_hdc1080\fP"
.br
.ti -1c
.RI "directory \fBesp_hmc5883l\fP"
.br
.ti -1c
.RI "directory \fBesp_ina226\fP"
.br
.ti -1c
.RI "directory \fBesp_ltr390uv\fP"
.br
.ti -1c
.RI "directory \fBesp_max30105\fP"
.br
.ti -1c
.RI "directory \fBesp_mlx90614\fP"
.br
.ti -1c
.RI "directory \fBesp_mmc56x3\fP"
.br
.ti -1c
.RI "directory \fBesp_mpu6050\fP"
.br
.ti -1c
.RI "directory \fBesp_sgp4x\fP"
.br
.ti -1c
.RI "directory \fBesp_sht4x\fP"
.br
.ti -1c
.RI "directory \fBesp_ssd1306\fP"
.br
.ti -1c
.RI "directory \fBesp_tbi2cxxx\fP"
.br
.ti -1c
.RI "directory \fBesp_tlv493d\fP"
.br
.ti -1c
.RI "directory \fBesp_veml6040\fP"
.br
.ti -1c
.RI "directory \fBesp_veml7700\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fR\fP \fR\fP \fR\fP \fR\fP \fR\fP \fR\fP

.PP
Welcome to the I2C peripheral components library with ESP-IDF support\&. This library of components is relatively active and updated on a regular basis and a list of operational components and the state of each component under development is available below\&.

.PP
ESP-IDF I2C device peripheral components supported at this time are listed as follows:

.PP
.IP "\(bu" 2
ASAIR AHTXX
.IP "\(bu" 2
AKM AK8975
.IP "\(bu" 2
AMS AS3935
.IP "\(bu" 2
OSRAM AS7341
.IP "\(bu" 2
ROHM BH1750FVI
.IP "\(bu" 2
Bosch BME680
.IP "\(bu" 2
Bosch BMP280
.IP "\(bu" 2
Bosch BMP390
.IP "\(bu" 2
ScioSense CCS811
.IP "\(bu" 2
ScioSense ENS160
.IP "\(bu" 2
Texas Instruments HDC1080
.IP "\(bu" 2
Honeywell HMC5883L
.IP "\(bu" 2
Texas Instruments INA226
.IP "\(bu" 2
Lite-On LTR390UV
.IP "\(bu" 2
Maxim-Integrated MAX30105 - Work in Progress
.IP "\(bu" 2
Melexis MLX90614
.IP "\(bu" 2
Memsic MMC56X3
.IP "\(bu" 2
InvenSense MPU6050
.IP "\(bu" 2
Sensirion SGP4X
.IP "\(bu" 2
Sensirion SHT4X
.IP "\(bu" 2
Generic SSD1306 (128x32 and 128x64)
.IP "\(bu" 2
Infineon TLV493D - Work in Progress
.IP "\(bu" 2
Vishay VEML6040
.IP "\(bu" 2
Vishay VEML7700
.PP

.PP
The above components have a dependency on the \fResp_type_utils\fP component that must be included in your project\&. This component includes transmit and receive buffers of various sizes, and byte manipulation features\&.

.PP
Components are developed when needed for product development and/or prototyping purposes, and shared with the ESP32 community for ESP-IDF developers\&. Custom component development is available upon request, please contact me directly, and I would be happy to discuss the details of your component needs\&. If any problems arise please feel free to log an issue and if you would to contribute please contact me\&.

.PP
Copyright (c) 2024 Eric Gionet (gionet.c.eric@gmail.com) 
