.TH "ccs811_thresholds_register_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccs811_thresholds_register_s \- CCS811 thresholds register structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ccs811\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ccs811_threshold_value_t \fBlow_to_med\fP"
.br
.ti -1c
.RI "ccs811_threshold_value_t \fBmed_to_high\fP"
.br
.ti -1c
.RI "uint8_t \fBhysteresis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CCS811 thresholds register structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t hysteresis"
threshold hysteresis value (50ppm = 0x default) 
.SS "ccs811_threshold_value_t low_to_med"
low to medium threshold (1500ppm = 0x05DC default) 
.SS "ccs811_threshold_value_t med_to_high"
medium to high threshold (2500ppm = 0x09C4 default) 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
