.TH "ccs811_measure_mode_row_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccs811_measure_mode_row_s \- CCS811 measure mode row definition structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ccs811\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBccs811_drive_modes_t\fP \fBmode\fP"
.br
.ti -1c
.RI "const char * \fBdesc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CCS811 measure mode row definition structure\&. 
.SH "Field Documentation"
.PP 
.SS "const char* desc"
drive mode description 
.SS "\fBccs811_drive_modes_t\fP mode"
drive mode 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
