.TH "datatable_event_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatable_event_tag \- Data-table event structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <datatable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdatatable_event_types_t\fP \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBmessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data-table event structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
