.TH "datatable_row_data_column_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatable_row_data_column_tag \- Data-table row data column structure\&. This structure is a data model that represents data storage of the record based on the data-table's column column data-type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <datatable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdatatable_id_column_data_type_t\fP \fBid_data\fP"
.br
.ti -1c
.RI "\fBdatatable_ts_column_data_type_t\fP \fBts_data\fP"
.br
.ti -1c
.RI "\fBdatatable_vector_column_data_type_t\fP \fBvector_data\fP"
.br
.ti -1c
.RI "\fBdatatable_bool_column_data_type_t\fP \fBbool_data\fP"
.br
.ti -1c
.RI "\fBdatatable_float_column_data_type_t\fP \fBfloat_data\fP"
.br
.ti -1c
.RI "\fBdatatable_int16_column_data_type_t\fP \fBint16_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data-table row data column structure\&. This structure is a data model that represents data storage of the record based on the data-table's column column data-type\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
