.TH "datatable_float_column_data_type_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatable_float_column_data_type_tag \- Data-table float data-type column structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <datatable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBvalue\fP"
.br
.ti -1c
.RI "time_t \fBvalue_ts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data-table float data-type column structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
