.TH "datatable_row_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatable_row_tag \- Data-table row structure\&. This structure is a data model that represents data storage of record by data-table row and configured data-table columns\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <datatable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdatatable_row_data_column_t\fP ** \fBdata_columns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data-table row structure\&. This structure is a data model that represents data storage of record by data-table row and configured data-table columns\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
