.TH "datatable_config_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatable_config_tag \- Data-table configuration structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <datatable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "uint8_t \fBcolumns_size\fP"
.br
.ti -1c
.RI "uint16_t \fBrows_size\fP"
.br
.ti -1c
.RI "\fBdatatable_data_storage_types_t\fP \fBdata_storage_type\fP"
.br
.ti -1c
.RI "\fBtime_into_interval_config_t\fP \fBsampling_config\fP"
.br
.ti -1c
.RI "\fBtime_into_interval_config_t\fP \fBprocessing_config\fP"
.br
.ti -1c
.RI "\fBdatatable_event\fP \fBevent_handler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data-table configuration structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t columns_size"
data-table column array size, 1\&.\&.255, this setting cannot be 0 
.SS "\fBdatatable_data_storage_types_t\fP data_storage_type"
data-table data storage type, defines handling of records when the data-table is full 
.SS "const char* name"
data-table textual name, maximum of 15 characters 
.SS "\fBtime_into_interval_config_t\fP processing_config"
data-table processing time-into-interval configuration, configures the processing interval 
.SS "uint16_t rows_size"
data-table row array size, 1\&.\&.65535, this setting cannot be 0 
.SS "\fBtime_into_interval_config_t\fP sampling_config"
data-table sampling time-into-interval configuration, configures the sampling interval 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
