.TH "datatable_column_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatable_column_tag \- Data-table column structure\&. The data-table record identifier and timestamp columns are created by default when the data-table is created\&. The record identifier and record timestamp data-types are excluded from data processing\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <datatable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBdatatable_column_name_t\fP \fBnames\fP [3]"
.br
.ti -1c
.RI "\fBdatatable_column_data_types_t\fP \fBdata_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data-table column structure\&. The data-table record identifier and timestamp columns are created by default when the data-table is created\&. The record identifier and record timestamp data-types are excluded from data processing\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
