.TH "datatable_int16_column_data_type_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatable_int16_column_data_type_tag \- Data-table int16 data-type column structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <datatable\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBvalue\fP"
.br
.ti -1c
.RI "time_t \fBvalue_ts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data-table int16 data-type column structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
