.TH "ds18b20_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ds18b20_context_t \- DS18B20 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ds18b20\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBds18b20_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "\fBonewire_bus_handle_t\fP \fBowb_handle\fP"
.br
.ti -1c
.RI "onewire_device_address_t \fBowb_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DS18B20 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBds18b20_config_t\fP dev_config"
ds18b20 device configuration 
.SS "onewire_device_address_t owb_address"
ds18b20 1-wire device address 
.SS "\fBonewire_bus_handle_t\fP owb_handle"
ds18b20 1-wire bus handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
