.TH "ens160_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ens160_context_t \- ENS160 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ens160\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBens160_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "uint16_t \fBpart_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ENS160 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBens160_config_t\fP dev_config"
ens160 configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
ens160 i2c device handle 
.SS "uint16_t part_id"
ens160 part identifier 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
