.TH "ens160_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ens160_config_s \- ENS160 configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ens160\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "bool \fBirq_enabled\fP"
.br
.ti -1c
.RI "bool \fBirq_data_enabled\fP"
.br
.ti -1c
.RI "bool \fBirq_gpr_enabled\fP"
.br
.ti -1c
.RI "\fBens160_interrupt_pin_drivers_t\fP \fBirq_pin_driver\fP"
.br
.ti -1c
.RI "\fBens160_interrupt_pin_polarities_t\fP \fBirq_pin_polarity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ENS160 configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t i2c_address"
ens160 i2c device address 
.SS "uint32_t i2c_clock_speed"
ens160 i2c device scl clock speed in hz 
.SS "bool irq_data_enabled"
true indicates interrupt pin is asserted when new data is available in \fRDATA_XXX\fP registers 
.SS "bool irq_enabled"
true indicates interrupt pin is enabled 
.SS "bool irq_gpr_enabled"
true indicates interrupt pin is asserted when new data is available in general purpose registers 
.SS "\fBens160_interrupt_pin_drivers_t\fP irq_pin_driver"
interrupt pin driver configuration 
.SS "\fBens160_interrupt_pin_polarities_t\fP irq_pin_polarity"
interrupt pin polarity configuration 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
