.TH "ens160_air_quality_raw_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ens160_air_quality_raw_data_s \- ENS160 air quality raw data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ens160\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBhp0_ri\fP"
.br
.ti -1c
.RI "uint32_t \fBhp1_ri\fP"
.br
.ti -1c
.RI "uint32_t \fBhp2_ri\fP"
.br
.ti -1c
.RI "uint32_t \fBhp3_ri\fP"
.br
.ti -1c
.RI "uint32_t \fBhp0_bl\fP"
.br
.ti -1c
.RI "uint32_t \fBhp1_bl\fP"
.br
.ti -1c
.RI "uint32_t \fBhp2_bl\fP"
.br
.ti -1c
.RI "uint32_t \fBhp3_bl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ENS160 air quality raw data structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
