.TH "ens160_aqi_uba_row_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ens160_aqi_uba_row_s \- ENS160 air quality index of the UBA row definition structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ens160\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBens160_aqi_uba_indexes_t\fP \fBindex\fP"
.br
.ti -1c
.RI "const char * \fBrating\fP"
.br
.ti -1c
.RI "const char * \fBhygienic_rating\fP"
.br
.ti -1c
.RI "const char * \fBrecommendation\fP"
.br
.ti -1c
.RI "const char * \fBexposure_limit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ENS160 air quality index of the UBA row definition structure\&. 
.SH "Field Documentation"
.PP 
.SS "const char* exposure_limit"
AQI-UBA exposure limit guidance 
.SS "const char* hygienic_rating"
AQI-UBA hygienic rating guidance 
.SS "\fBens160_aqi_uba_indexes_t\fP index"
AQI-UBA index rating 
.SS "const char* rating"
AQI-UBA rating category 
.SS "const char* recommendation"
AQI-UBA recommendation 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
