.TH "ens160_air_quality_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ens160_air_quality_data_s \- ENS160 air quality data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ens160\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBens160_aqi_uba_indexes_t\fP \fBuba_aqi\fP"
.br
.ti -1c
.RI "uint16_t \fBtvoc\fP"
.br
.ti -1c
.RI "uint16_t \fBetoh\fP"
.br
.ti -1c
.RI "uint16_t \fBeco2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ENS160 air quality data structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t eco2"
ENS160 calculated equivalent co2 concentration in ppm 
.SS "uint16_t etoh"
ENS160 calculated etoh in ppb 
.SS "uint16_t tvoc"
ENS160 calculated tvoc in ppb 
.SS "\fBens160_aqi_uba_indexes_t\fP uba_aqi"
ENS160 air quality index according to the UBA 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
