.TH "ens160_app_version_u" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ens160_app_version_u \- ENS160 application version register structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ens160\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBmajor\fP"
.br
.ti -1c
.RI "uint8_t \fBminor\fP"
.br
.ti -1c
.RI "uint8_t \fBrelease\fP"
.br
.ti -1c
.RI "uint8_t \fBbytes\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
ENS160 application version register structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t bytes[3]"
represents app version as a byte array\&. 
.SS "uint8_t major"
ens160 major firmware version 
.SS "uint8_t minor"
ens160 minor firmware version 
.SS "uint8_t release"
ens160 firmware version release 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
