.TH "GasIndexAlgorithmParams" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GasIndexAlgorithmParams
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sensirion_gas_index_algorithm\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmAlgorithm_Type\fP"
.br
.ti -1c
.RI "float \fBmSamplingInterval\fP"
.br
.ti -1c
.RI "float \fBmIndex_Offset\fP"
.br
.ti -1c
.RI "int32_t \fBmSraw_Minimum\fP"
.br
.ti -1c
.RI "float \fBmGating_Max_Duration_Minutes\fP"
.br
.ti -1c
.RI "float \fBmInit_Duration_Mean\fP"
.br
.ti -1c
.RI "float \fBmInit_Duration_Variance\fP"
.br
.ti -1c
.RI "float \fBmGating_Threshold\fP"
.br
.ti -1c
.RI "float \fBmIndex_Gain\fP"
.br
.ti -1c
.RI "float \fBmTau_Mean_Hours\fP"
.br
.ti -1c
.RI "float \fBmTau_Variance_Hours\fP"
.br
.ti -1c
.RI "float \fBmSraw_Std_Initial\fP"
.br
.ti -1c
.RI "float \fBmUptime\fP"
.br
.ti -1c
.RI "float \fBmSraw\fP"
.br
.ti -1c
.RI "float \fBmGas_Index\fP"
.br
.ti -1c
.RI "bool \fBm_Mean_Variance_Estimator___Initialized\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Mean\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Sraw_Offset\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Std\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Gamma_Mean\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Gamma_Variance\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Gamma_Initial_Mean\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Gamma_Initial_Variance\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator__Gamma_Mean\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator__Gamma_Variance\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Uptime_Gamma\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Uptime_Gating\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Gating_Duration_Minutes\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Sigmoid__K\fP"
.br
.ti -1c
.RI "float \fBm_Mean_Variance_Estimator___Sigmoid__X0\fP"
.br
.ti -1c
.RI "float \fBm_Mox_Model__Sraw_Std\fP"
.br
.ti -1c
.RI "float \fBm_Mox_Model__Sraw_Mean\fP"
.br
.ti -1c
.RI "float \fBm_Sigmoid_Scaled__K\fP"
.br
.ti -1c
.RI "float \fBm_Sigmoid_Scaled__X0\fP"
.br
.ti -1c
.RI "float \fBm_Sigmoid_Scaled__Offset_Default\fP"
.br
.ti -1c
.RI "float \fBm_Adaptive_Lowpass__A1\fP"
.br
.ti -1c
.RI "float \fBm_Adaptive_Lowpass__A2\fP"
.br
.ti -1c
.RI "bool \fBm_Adaptive_Lowpass___Initialized\fP"
.br
.ti -1c
.RI "float \fBm_Adaptive_Lowpass___X1\fP"
.br
.ti -1c
.RI "float \fBm_Adaptive_Lowpass___X2\fP"
.br
.ti -1c
.RI "float \fBm_Adaptive_Lowpass___X3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct to hold all parameters and states of the gas algorithm\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
