.TH "hmc5883l_gain_error_axes_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc5883l_gain_error_axes_data_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx_axis\fP"
.br
.ti -1c
.RI "float \fBy_axis\fP"
.br
.ti -1c
.RI "float \fBz_axis\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float x_axis"
x axis 
.SS "float y_axis"
y axis 
.SS "float z_axis"
z axis 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
