.TH "hmc5883l_magnetic_axes_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc5883l_magnetic_axes_data_s
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hmc5883l\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx_axis\fP"
.br
.ti -1c
.RI "float \fBy_axis\fP"
.br
.ti -1c
.RI "float \fBz_axis\fP"
.br
.ti -1c
.RI "float \fBheading\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HMC5883L measurement result, milligauss 
.SH "Field Documentation"
.PP 
.SS "float heading"
heading in degrees 
.SS "float x_axis"
x axis mG 
.SS "float y_axis"
y axis mG 
.SS "float z_axis"
z axis mG 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
