.TH "hmc5883l_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc5883l_context_t \- HMC5883L context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hmc5883l\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBhmc5883l_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "uint32_t \fBdev_id\fP"
.br
.ti -1c
.RI "float \fBdeclination\fP"
.br
.ti -1c
.RI "bool \fBgain_calibrated\fP"
.br
.ti -1c
.RI "bool \fBoffset_calibrated\fP"
.br
.ti -1c
.RI "\fBhmc5883l_offset_axes_data_t\fP \fBoffset_axes\fP"
.br
.ti -1c
.RI "\fBhmc5883l_gain_error_axes_data_t\fP \fBgain_error_axes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HMC5883L context structure\&. 
.SH "Field Documentation"
.PP 
.SS "float declination"
magnetic declination angle http://www.magnetic-declination.com/ 
.SS "i2c_master_dev_handle_t i2c_handle"
I2C device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
