.TH "hmc5883l_axes_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmc5883l_axes_data_s
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <hmc5883l\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBx_axis\fP"
.br
.ti -1c
.RI "int16_t \fBy_axis\fP"
.br
.ti -1c
.RI "int16_t \fBz_axis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
HMC5883L raw measurement result 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
