.TH "i2c_sht4x_data___t::humidity_tag" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
i2c_sht4x_data___t::humidity_tag
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBhumidity_data_tag\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union \fBi2c_sht4x_data___t::humidity_tag::humidity_data_tag\fP \fBhumidity_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
