.TH "i2c_sht4x_data___t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
i2c_sht4x_data___t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sht4x\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhumidity_tag\fP"
.br
.ti -1c
.RI "struct \fBtemperature_tag\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBbytes\fP [6]"
.br
.ti -1c
.RI "struct \fBi2c_sht4x_data___t::temperature_tag\fP \fBtemperature\fP"
.br
.ti -1c
.RI "struct \fBi2c_sht4x_data___t::humidity_tag\fP \fBhumidity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
public enumerator, union, and structure definitions 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
