.TH "ina226_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ina226_context_t \- INA226 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ina226\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBina226_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "float \fBcurrent_lsb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
INA226 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "float current_lsb"
ina226 current LSB value, uA/bit, this is automatically configured 
.SS "\fBina226_config_t\fP dev_config"
ina226 device configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
ina226 I2C device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
