.TH "kalman_motion_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kalman_motion_t \- Kalman motion state structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <kalman_motion\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBq_angle\fP"
.br
.ti -1c
.RI "float \fBq_bias\fP"
.br
.ti -1c
.RI "float \fBr_measure\fP"
.br
.ti -1c
.RI "float \fBangle\fP"
.br
.ti -1c
.RI "float \fBbias\fP"
.br
.ti -1c
.RI "float \fBrate\fP"
.br
.ti -1c
.RI "float \fBp\fP [2][2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Kalman motion state structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
