.TH "components/peripherals/spi/esp_max31865/max31865.h" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/spi/esp_max31865/max31865.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <esp_err\&.h>\fP
.br
\fR#include <driver/gpio\&.h>\fP
.br
\fR#include <driver/spi_common\&.h>\fP
.br
\fR#include <driver/spi_master\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBspi_max31865_config_t\fP"
.br
.RI "MAX31865 SPI device configuration structure\&. "
.ti -1c
.RI "struct \fBspi_max31865_t\fP"
.br
.RI "MAX31865 SPI device structure\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2C_MAX31865_SCL_SPEED_HZ\fP   UINT32_C(100000)"
.br
.RI "max31865 I2C default clock frequency (100KHz) "
.ti -1c
.RI "#define \fBSPI_MAX31865_DEV_ADDR\fP   UINT8_C(0x38)"
.br
.RI "max31865 I2C address "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct spi_max31865_t \fBspi_max31865_t\fP"
.br
.RI "MAX31865 SPI device structure definitions\&. "
.ti -1c
.RI "typedef struct \fBspi_max31865_t\fP * \fBspi_max31865_handle_t\fP"
.br
.RI "MAX31865 SPI device handle structure\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBspi_max31865_fault_detection_cycles_t\fP { \fBSPI_MAX31865_FAULT_DETECT_FINISHED\fP = (0b00), \fBSPI_MAX31865_FAULT_DETECT_STILL_RUNNING\fP = (0b01), \fBSPI_MAX31865_FAULT_DETECT_CYCLE1_RUNNING\fP = (0b10), \fBSPI_MAX31865_FAULT_DETECT_CYCLE2_RUNNING\fP = (0b11) }"
.br
.ti -1c
.RI "enum \fBspi_max31865_modes_t\fP { \fBSPI_MAX31865_MODE_SINGLE\fP = 0, \fBSPI_MAX31865_MODE_AUTO\fP }"
.br
.ti -1c
.RI "enum \fBspi_max31865_filters_t\fP { \fBSPI_MAX31865_FILTER_60HZ\fP = 0, \fBSPI_MAX31865_FILTER_50HZ\fP }"
.br
.ti -1c
.RI "enum \fBspi_max31865_connection_types_t\fP { \fBSPI_MAX31865_2WIRE_OR_4WIRE\fP = 0, \fBSPI_MAX31865_3WIRE\fP = 1 }"
.br
.ti -1c
.RI "enum \fBspi_max31865_standards_t\fP { \fBSPI_MAX31865_ITS90\fP = 0, \fBSPI_MAX31865_DIN43760\fP, \fBSPI_MAX31865_US_INDUSTRIAL\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "union \fB__attribute__\fP ((packed)) ahtxx_status_register_u"
.br
.RI "AHTXX status register structure definition\&. "
.ti -1c
.RI "esp_err_t \fBspi_max31865_get_configuration_register\fP (\fBspi_max31865_handle_t\fP max31865_handle)"
.br
.ti -1c
.RI "esp_err_t \fBspi_max31865_set_configuration_register\fP (\fBspi_max31865_handle_t\fP max31865_handle, const spi_max31865_configuration_register_t config_reg)"
.br
.ti -1c
.RI "esp_err_t \fBspi_max31865_get_fault_status_register\fP (\fBspi_max31865_handle_t\fP max31865_handle)"
.br
.RI "Read fault status register from MAX31865\&. "
.ti -1c
.RI "esp_err_t \fBspi_max31865_init\fP (const \fBspi_max31865_config_t\fP *max31865_config, \fBspi_max31865_handle_t\fP *max31865_handle)"
.br
.RI "Initializes an MAX31865 device onto the I2C master bus\&. "
.ti -1c
.RI "esp_err_t \fBspi_max31865_get_measurement\fP (\fBspi_max31865_handle_t\fP max31865_handle, float *const temperature)"
.br
.RI "Reads temperature from MAX31865\&. "
.ti -1c
.RI "esp_err_t \fBspi_max31865_remove\fP (\fBspi_max31865_handle_t\fP max31865_handle)"
.br
.RI "Removes an MAX31865 device from master bus\&. "
.ti -1c
.RI "esp_err_t \fBspi_max31865_delete\fP (\fBspi_max31865_handle_t\fP max31865_handle)"
.br
.RI "Removes an MAX31865 device from master bus and frees handle\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBspi_max31865_configuration_register_t\fP"
.br
.ti -1c
.RI "\fBspi_max31865_fault_status_register_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
