.TH "md_components_2peripherals_2owb_2onewire__bus_2_c_h_a_n_g_e_l_o_g" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_components_2peripherals_2owb_2onewire__bus_2_c_h_a_n_g_e_l_o_g \- 1\&.0\&.2 
.PP


.PP
.IP "\(bu" 2
raise recovery time to support more sensor on longer wire (d0b2b52)
.PP
.SH "1\&.0\&.0"
.PP
.IP "\(bu" 2
Initial driver version, with the RMT driver as backend controller 
.PP

