.TH "mlx90614_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mlx90614_context_t \- MLX90614 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mlx90614\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmlx90614_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "uint32_t \fBident_number_hi\fP"
.br
.ti -1c
.RI "uint32_t \fBident_number_lo\fP"
.br
.ti -1c
.RI "float \fBpwm_period_multiplier\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MLX90614 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBmlx90614_config_t\fP dev_config"
mlx90614 configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
mlx90614 I2C device handle 
.SS "uint32_t ident_number_hi"
mlx90614 device identification number 32-bit hi 
.SS "uint32_t ident_number_lo"
mlx90614 device identification number 32-bit lo 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
