.TH "mmc56x3_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mmc56x3_config_s \- MMC56X3 configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mmc56x3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "uint16_t \fBdata_rate\fP"
.br
.ti -1c
.RI "bool \fBcontinuous_mode_enabled\fP"
.br
.ti -1c
.RI "\fBmmc56x3_measurement_times_t\fP \fBmeasurement_bandwidth\fP"
.br
.ti -1c
.RI "bool \fBauto_sr_enabled\fP"
.br
.ti -1c
.RI "float \fBdeclination\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MMC56X3 configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "bool auto_sr_enabled"
mmc56x3 auto set-reset configuration 
.SS "bool continuous_mode_enabled"
mmc56x3 device measurement mode configuration, data rate must be non-zero when enabled 
.SS "uint16_t data_rate"
mmc56x3 device data rate (odr), 0-255 or 1000 for 1000Hz data rate configuration 
.SS "float declination"
magnetic declination angle http://www.magnetic-declination.com/ 
.SS "uint16_t i2c_address"
mmc56x3 i2c device address 
.SS "uint32_t i2c_clock_speed"
mmc56x3 i2c device scl clock speed 
.SS "\fBmmc56x3_measurement_times_t\fP measurement_bandwidth"
mmc56x3 device measurement bandwith configuration 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
