.TH "mmc56x3_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mmc56x3_context_t \- MMC56X3 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mmc56x3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmmc56x3_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "uint8_t \fBproduct_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MMC56X3 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "i2c_master_dev_handle_t i2c_handle"
I2C device handle 
.SS "uint8_t product_id"
mmc56x3 product identifier 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
