.TH "mmc56x3_magnetic_axes_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mmc56x3_magnetic_axes_data_s \- MMC56X3 magnetic axes data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mmc56x3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx_axis\fP"
.br
.ti -1c
.RI "float \fBy_axis\fP"
.br
.ti -1c
.RI "float \fBz_axis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MMC56X3 magnetic axes data structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
