.TH "mpu6050_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpu6050_config_s \- MPU6050 configuration structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mpu6050\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "\fBmpu6050_digital_low_pass_filters_t\fP \fBlow_pass_filter\fP"
.br
.ti -1c
.RI "\fBmpu6050_gyro_clock_sources_t\fP \fBgyro_clock_source\fP"
.br
.ti -1c
.RI "\fBmpu6050_gyro_full_scale_ranges_t\fP \fBgyro_full_scale_range\fP"
.br
.ti -1c
.RI "\fBmpu6050_accel_full_scale_ranges_t\fP \fBaccel_full_scale_range\fP"
.br
.ti -1c
.RI "gpio_num_t \fBirq_io_num\fP"
.br
.ti -1c
.RI "mpu6050_irq_pin_active_level_t \fBirq_io_active_level\fP"
.br
.ti -1c
.RI "mpu6050_irq_pin_mode_t \fBirq_io_mode\fP"
.br
.ti -1c
.RI "mpu6050_irq_latch_t \fBirq_latch\fP"
.br
.ti -1c
.RI "mpu6050_irq_clear_t \fBirq_clear_behavior\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MPU6050 configuration structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "\fBmpu6050_accel_full_scale_ranges_t\fP accel_full_scale_range"
mpu6050 accelerometer full scale range configuration 
.SS "\fBmpu6050_gyro_clock_sources_t\fP gyro_clock_source"
mpu6050 gyroscope clock source configuration 
.SS "\fBmpu6050_gyro_full_scale_ranges_t\fP gyro_full_scale_range"
mpu6050 gyroscope full scale range configuration 
.SS "uint16_t i2c_address"
mpu6050 i2c device address 
.SS "uint32_t i2c_clock_speed"
mpu6050 i2c device scl clock speed in hz 
.SS "mpu6050_irq_clear_t irq_clear_behavior"
Interrupt status clear behavior 
.SS "mpu6050_irq_pin_active_level_t irq_io_active_level"
Active level of mpu6050 INT pin 
.SS "mpu6050_irq_pin_mode_t irq_io_mode"
Push-pull or open drain mode for INT pin 
.SS "gpio_num_t irq_io_num"
mpu6050 GPIO interrupt pin 
.SS "mpu6050_irq_latch_t irq_latch"
The interrupt pulse behavior of INT pin 
.SS "\fBmpu6050_digital_low_pass_filters_t\fP low_pass_filter"
mpu6050 digital low-pass filter configuration 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
