.TH "mpu6050_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpu6050_context_t \- MPU6050 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mpu6050\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmpu6050_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "float \fBaccel_sensitivity\fP"
.br
.ti -1c
.RI "float \fBgyro_sensitivity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MPU6050 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "float accel_sensitivity"
mpu6050 accelerometer sensitivity value 
.SS "\fBmpu6050_config_t\fP dev_config"
mpu6050 device configuration 
.SS "float gyro_sensitivity"
mpu6050 gyroscope sensitivity value 
.SS "i2c_master_dev_handle_t i2c_handle"
mpu6050 I2C device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
