.TH "onewire_device_iter_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
onewire_device_iter_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBonewire_bus_handle_t\fP \fBbus\fP"
.br
.ti -1c
.RI "uint16_t \fBlast_discrepancy\fP"
.br
.ti -1c
.RI "bool \fBis_last_device\fP"
.br
.ti -1c
.RI "uint8_t \fBrom_number\fP [sizeof(onewire_device_address_t)]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
