.TH "onewire_bus_config_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
onewire_bus_config_t \- 1-Wire bus configuration  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <onewire_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbus_gpio_num\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
1-Wire bus configuration 
.SH "Field Documentation"
.PP 
.SS "int bus_gpio_num"
GPIO number that used by the 1-Wire bus 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
