.TH "onewire_bus_rmt_config_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
onewire_bus_rmt_config_t \- 1-Wire bus RMT specific configuration  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <onewire_bus_impl_rmt\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBmax_rx_bytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
1-Wire bus RMT specific configuration 
.SH "Field Documentation"
.PP 
.SS "uint32_t max_rx_bytes"
Set the largest possible single receive size, which determins the size of the internal buffer that used to save the receiving RMT symbols 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
