.TH "pressure_tendency_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pressure_tendency_t \- Pressure tendency structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <pressure_tendency\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBsamples_count\fP"
.br
.ti -1c
.RI "uint16_t \fBsamples_size\fP"
.br
.ti -1c
.RI "float * \fBsamples\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pressure tendency structure\&. 
.SH "Field Documentation"
.PP 
.SS "float* samples"
pressure tendency samples array, state machine variable 
.SS "uint16_t samples_count"
pressure tendency samples count, state machine variable 
.SS "uint16_t samples_size"
pressure tendency samples size, state machine variable 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
