.TH "components/utilities/esp_math3d/quaternion.c" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/utilities/esp_math3d/quaternion.c
.SH SYNOPSIS
.br
.PP
\fR#include 'quaternion\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <esp_log\&.h>\fP
.br
\fR#include <esp_check\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBESP_ARG_CHECK\fP(VAL)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fBquaternion_init\fP (\fBquaternion_handle_t\fP *quaternion_handle)"
.br
.ti -1c
.RI "esp_err_t \fBquaternion_init_data\fP (\fBquaternion_handle_t\fP quaternion_handle, float nw, float nx, float ny, float nz)"
.br
.ti -1c
.RI "esp_err_t \fBquaternion_get_product\fP (\fBquaternion_handle_t\fP quaternion_handle, \fBquaternion_handle_t\fP *product_handle)"
.br
.ti -1c
.RI "esp_err_t \fBquaternion_get_conjugate\fP (\fBquaternion_handle_t\fP quaternion_handle, \fBquaternion_handle_t\fP *conjugate_handle)"
.br
.ti -1c
.RI "esp_err_t \fBquaternion_get_magnitude\fP (\fBquaternion_handle_t\fP quaternion_handle, float *magnitude)"
.br
.ti -1c
.RI "esp_err_t \fBquaternion_normalize\fP (\fBquaternion_handle_t\fP quaternion_handle)"
.br
.ti -1c
.RI "esp_err_t \fBquaternion_get_normalized\fP (\fBquaternion_handle_t\fP quaternion_handle, \fBquaternion_handle_t\fP *normalized_handle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESP-IDF math 3d library

.PP
Ported from esp-open-rtos

.PP
Copyright (c) 2024 Eric Gionet (gionet.c.eric@gmail.com)

.PP
MIT Licensed as described in the file LICENSE 
.SH "Macro Definition Documentation"
.PP 
.SS "#define ESP_ARG_CHECK( VAL)"
\fBValue:\fP
.nf
do { if (!(VAL)) return ESP_ERR_INVALID_ARG; } while (0)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
