.TH "components/peripherals/adc/esp_s12sd/include/s12sd.h" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/adc/esp_s12sd/include/s12sd.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <esp_check\&.h>\fP
.br
\fR#include <esp_err\&.h>\fP
.br
\fR#include <esp_adc/adc_oneshot\&.h>\fP
.br
\fR#include <esp_adc/adc_cali\&.h>\fP
.br
\fR#include <esp_adc/adc_cali_scheme\&.h>\fP
.br
\fR#include 's12sd_version\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs12sd_config_s\fP"
.br
.RI "S12SD configuration structure definition\&. "
.ti -1c
.RI "struct \fBs12sd_context_t\fP"
.br
.RI "S12SD context structure\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC_S12SD_UNIT_DEFAULT\fP   ADC_UNIT_1"
.br
.ti -1c
.RI "#define \fBADC_S12SD_CHANNEL_DEFAULT\fP   ADC_CHANNEL_0"
.br
.ti -1c
.RI "#define \fBADC_S12SD_SAMPLE_SIZE\fP   (1000)"
.br
.ti -1c
.RI "#define \fBADC_S12SD_ATTEN\fP   ADC_ATTEN_DB_12"
.br
.ti -1c
.RI "#define \fBADC_S12SD_DIGI_BIT_WIDTH\fP   (12)"
.br
.RI "adc bit width at 12-bits "
.ti -1c
.RI "#define \fBADC_S12SD_CONFIG_DEFAULT\fP"
.br
.RI "Macro that initializes \fRadc_s12sd_config_t\fP to default configuration settings\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs12sd_config_s\fP \fBs12sd_config_t\fP"
.br
.RI "S12SD configuration structure definition\&. "
.ti -1c
.RI "typedef struct s12sd_context_t \fBs12sd_context_t\fP"
.br
.RI "S12SD context structure definition\&. "
.ti -1c
.RI "typedef struct \fBs12sd_context_t\fP * \fBs12sd_handle_t\fP"
.br
.RI "S12SD handle structure definition\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fBs12sd_init\fP (const \fBs12sd_config_t\fP *s12sd_config, \fBs12sd_handle_t\fP *s12sd_handle)"
.br
.RI "Initializes an adc S12SD device\&. "
.ti -1c
.RI "esp_err_t \fBs12sd_measure\fP (\fBs12sd_handle_t\fP handle, uint8_t *uv_index)"
.br
.RI "Measure S12SD device\&. "
.ti -1c
.RI "esp_err_t \fBs12sd_delete\fP (\fBs12sd_handle_t\fP handle)"
.br
.RI "Deinitialize S12SD device\&. "
.ti -1c
.RI "const char * \fBs12sd_get_fw_version\fP (void)"
.br
.RI "Converts S12SD firmware version numbers (major, minor, patch) into a string\&. "
.ti -1c
.RI "int32_t \fBs12sd_get_fw_version_number\fP (void)"
.br
.RI "Converts S12SD firmware version numbers (major, minor, patch) into an integer value\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
