.TH "s12sd_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s12sd_config_s \- S12SD configuration structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <s12sd\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBadc_unit\fP"
.br
.ti -1c
.RI "uint8_t \fBadc_channel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
S12SD configuration structure definition\&. 

public enumerator, union, and structure definitions 
.SH "Field Documentation"
.PP 
.SS "uint8_t adc_channel"
s12sd adc channel 
.SS "uint8_t adc_unit"
s12sd adc unit 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
