.TH "s12sd_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s12sd_context_t \- S12SD context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <s12sd\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBs12sd_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "adc_oneshot_unit_handle_t \fBadc_handle\fP"
.br
.ti -1c
.RI "adc_cali_handle_t \fBadc_cal_handle\fP"
.br
.ti -1c
.RI "bool \fBadc_calibrate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
S12SD context structure\&. 
.SH "Field Documentation"
.PP 
.SS "adc_cali_handle_t adc_cal_handle"
s12sd adc calibration handle 
.SS "bool adc_calibrate"
s12sd adc calibration initialization flag 
.SS "adc_oneshot_unit_handle_t adc_handle"
s12sd adc device handle 
.SS "\fBs12sd_config_t\fP dev_config"
s12sd adc configuration 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
