.TH "sgp4x_config_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sgp4x_config_t \- SGP4X device configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sgp4x\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "\fBsgp4x_versions_t\fP \fBdev_version\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SGP4X device configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBsgp4x_versions_t\fP dev_version"
sgp4x version 
.SS "uint16_t i2c_address"
sgp4x i2c device address 
.SS "uint32_t i2c_clock_speed"
sgp4x i2c device scl clock speed 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
