.TH "sht4x_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sht4x_context_t \- SHT4X context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sht4x\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsht4x_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "uint32_t \fBserial_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SHT4X context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBsht4x_config_t\fP dev_config"
sht4x device configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
sht4x i2c device handle 
.SS "uint32_t serial_number"
sht4x device serial number 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
