.TH "spi_max31865_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spi_max31865_t \- MAX31865 SPI device structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <max31865\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "SemaphoreHandle_t \fBspi_ready_sem\fP"
.br
.ti -1c
.RI "\fBspi_max31865_config_t\fP \fBspi_dev_config\fP"
.br
.ti -1c
.RI "spi_device_handle_t \fBspi_dev_handle\fP"
.br
.ti -1c
.RI "spi_max31865_configuration_register_t \fBconfig_reg\fP"
.br
.ti -1c
.RI "\fBspi_max31865_standards_t\fP \fBstandard\fP"
.br
.ti -1c
.RI "float \fBr_ref\fP"
.br
.ti -1c
.RI "float \fBrtd_nominal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
MAX31865 SPI device structure\&. 
.SH "Field Documentation"
.PP 
.SS "spi_max31865_configuration_register_t config_reg"
status register 
.SS "float r_ref"
Reference resistor value, Ohms 
.SS "float rtd_nominal"
RTD nominal resistance at 0 deg\&. C, Ohms (PT100 - 100 Ohms, PT1000 - 1000 Ohms) 
.SS "\fBspi_max31865_config_t\fP spi_dev_config"
SPI device configuration 
.SS "spi_device_handle_t spi_dev_handle"
SPI device handle 
.SS "SemaphoreHandle_t spi_ready_sem"
SPI semaphore for ready signal 
.SS "\fBspi_max31865_standards_t\fP standard"
Temperature scale standard 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
