.TH "ssd1306_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssd1306_config_s \- SSD1306 configuration structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ssd1306\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "\fBssd1306_panel_sizes_t\fP \fBpanel_size\fP"
.br
.ti -1c
.RI "uint8_t \fBoffset_x\fP"
.br
.ti -1c
.RI "bool \fBflip_enabled\fP"
.br
.ti -1c
.RI "bool \fBdisplay_enabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SSD1306 configuration structure definition\&. 
.SH "Field Documentation"
.PP 
.SS "bool display_enabled"
ssd1306 display is on when true otherwise it is off and sleeping 
.SS "bool flip_enabled"
ssd1306 displayed information is flipped when true 
.SS "uint16_t i2c_address"
ssd1306 i2c device address 
.SS "uint32_t i2c_clock_speed"
ssd1306 i2c device scl clock speed 
.SS "uint8_t offset_x"
ssd1306 x-axis offset 
.SS "\fBssd1306_panel_sizes_t\fP panel_size"
ssd1306 panel size 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
