.TH "components/peripherals/i2c/esp_ssd1306/include/ssd1306.h" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/i2c/esp_ssd1306/include/ssd1306.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <esp_err\&.h>\fP
.br
\fR#include <driver/i2c_master\&.h>\fP
.br
\fR#include <type_utils\&.h>\fP
.br
\fR#include 'ssd1306_version\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBssd1306_page_s\fP"
.br
.RI "SSD1306 page structure definition\&. "
.ti -1c
.RI "struct \fBssd1306_panel_s\fP"
.br
.RI "SSD1306 panel structure definition\&. "
.ti -1c
.RI "struct \fBssd1306_bdf_font_s\fP"
.br
.RI "SSD1306 BDF font structure definition\&. "
.ti -1c
.RI "struct \fBssd1306_config_s\fP"
.br
.RI "SSD1306 configuration structure definition\&. "
.ti -1c
.RI "struct \fBssd1306_context_t\fP"
.br
.RI "SSD1306 context structure\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2C_SSD1306_DEV_CLK_SPD\fP   UINT32_C(100000)"
.br
.RI "ssd1306 I2C default clock frequency (100KHz) "
.ti -1c
.RI "#define \fBI2C_SSD1306_DEV_ADDR\fP   UINT8_C(0x3c)"
.br
.RI "ssd1306 I2C address "
.ti -1c
.RI "#define \fBI2C_XFR_TIMEOUT_MS\fP   (500)"
.br
.RI "I2C transaction timeout in milliseconds\&. "
.ti -1c
.RI "#define \fBSSD1306_PAGE_SEGMENT_SIZE\fP   128"
.br
.RI "ssd1306 segment size "
.ti -1c
.RI "#define \fBSSD1306_PAGE_128x32_SIZE\fP   4"
.br
.RI "ssd1306 128x32 page size "
.ti -1c
.RI "#define \fBSSD1306_PAGE_128x64_SIZE\fP   8"
.br
.RI "ssd1306 128x64 page size "
.ti -1c
.RI "#define \fBSSD1306_PAGE_128x128_SIZE\fP   16"
.br
.RI "ssd1306 128x128 page size "
.ti -1c
.RI "#define \fBSSD1306_PANEL_128x32_WIDTH\fP   128"
.br
.RI "ssd1306 128x32 panel width "
.ti -1c
.RI "#define \fBSSD1306_PANEL_128x64_WIDTH\fP   128"
.br
.RI "ssd1306 128x64 panel width "
.ti -1c
.RI "#define \fBSSD1306_PANEL_128x128_WIDTH\fP   128"
.br
.RI "ssd1306 128x128 panel width "
.ti -1c
.RI "#define \fBSSD1306_PANEL_128x32_HEIGHT\fP   32"
.br
.RI "ssd1306 128x32 panel height "
.ti -1c
.RI "#define \fBSSD1306_PANEL_128x64_HEIGHT\fP   64"
.br
.RI "ssd1306 128x64 panel height "
.ti -1c
.RI "#define \fBSSD1306_PANEL_128x128_HEIGHT\fP   128"
.br
.RI "ssd1306 128x128 panel height "
.ti -1c
.RI "#define \fBI2C_SSD1306_128x32_CONFIG_DEFAULT\fP"
.br
.RI "Macro that initializes \fR\fBssd1306_config_t\fP\fP to default configuration settings for a 128x32 display\&. "
.ti -1c
.RI "#define \fBI2C_SSD1306_128x64_CONFIG_DEFAULT\fP"
.br
.RI "Macro that initializes \fR\fBssd1306_config_t\fP\fP to default configuration settings for a 128x64 display\&. "
.ti -1c
.RI "#define \fBI2C_SSD1306_128x128_CONFIG_DEFAULT\fP"
.br
.RI "Macro that initializes \fR\fBssd1306_config_t\fP\fP to default configuration settings for a 128x128 display\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBssd1306_scroll_frames_e\fP \fBssd1306_scroll_frames_t\fP"
.br
.RI "SSD1306 scroll step in terms of frame frequency enumerator definition\&. "
.ti -1c
.RI "typedef enum \fBssd1306_scroll_types_e\fP \fBssd1306_scroll_types_t\fP"
.br
.RI "SSD1306 scroll types enumerator definition\&. "
.ti -1c
.RI "typedef enum \fBssd1306_panel_sizes_e\fP \fBssd1306_panel_sizes_t\fP"
.br
.RI "SSD1306 panel sizes enumerator definition\&. "
.ti -1c
.RI "typedef struct \fBssd1306_page_s\fP \fBssd1306_page_t\fP"
.br
.RI "SSD1306 page structure definition\&. "
.ti -1c
.RI "typedef struct \fBssd1306_panel_s\fP \fBssd1306_panel_t\fP"
.br
.RI "SSD1306 panel structure definition\&. "
.ti -1c
.RI "typedef struct \fBssd1306_bdf_font_s\fP \fBssd1306_bdf_font_t\fP"
.br
.RI "SSD1306 BDF font structure definition\&. "
.ti -1c
.RI "typedef struct \fBssd1306_config_s\fP \fBssd1306_config_t\fP"
.br
.RI "SSD1306 configuration structure definition\&. "
.ti -1c
.RI "typedef struct ssd1306_context_t \fBssd1306_context_t\fP"
.br
.RI "SSD1306 context structure definition\&. "
.ti -1c
.RI "typedef struct \fBssd1306_context_t\fP * \fBssd1306_handle_t\fP"
.br
.RI "SSD1306 handle stucture definition\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBssd1306_scroll_frames_e\fP { \fBSSD1306_SCROLL_5_FRAMES\fP = 0b000, \fBSSD1306_SCROLL_64_FRAMES\fP = 0b001, \fBSSD1306_SCROLL_128_FRAMES\fP = 0b010, \fBSSD1306_SCROLL_256_FRAMES\fP = 0b011, \fBSSD1306_SCROLL_3_FRAMES\fP = 0b100, \fBSSD1306_SCROLL_4_FRAMES\fP = 0b101, \fBSSD1306_SCROLL_25_FRAMES\fP = 0b110, \fBSSD1306_SCROLL_2_FRAMES\fP = 0b111 }"
.br
.RI "SSD1306 scroll step in terms of frame frequency enumerator definition\&. "
.ti -1c
.RI "enum \fBssd1306_scroll_types_e\fP { \fBSSD1306_SCROLL_RIGHT\fP = 1, \fBSSD1306_SCROLL_LEFT\fP = 2, \fBSSD1306_SCROLL_DOWN\fP = 3, \fBSSD1306_SCROLL_UP\fP = 4, \fBSSD1306_SCROLL_STOP\fP = 5 }"
.br
.RI "SSD1306 scroll types enumerator definition\&. "
.ti -1c
.RI "enum \fBssd1306_panel_sizes_e\fP { \fBSSD1306_PANEL_128x32\fP = 0, \fBSSD1306_PANEL_128x64\fP = 1, \fBSSD1306_PANEL_128x128\fP = 2 }"
.br
.RI "SSD1306 panel sizes enumerator definition\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fBssd1306_load_bitmap_font\fP (const uint8_t *font, int encoding, uint8_t *bitmap, \fBssd1306_bdf_font_t\fP *const bdf_font)"
.br
.RI "Loads a BDF bitmap font and BDF font structure from a font file\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_bdf_text\fP (\fBssd1306_handle_t\fP handle, const uint8_t *font, const char *text, int xpos, int ypos)"
.br
.RI "Displays text on the SSD1306 with BDF font support\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_bdf_code\fP (\fBssd1306_handle_t\fP handle, const uint8_t *font, int code, int xpos, int ypos)"
.br
.RI "Displays BDF font code on the SSD1306\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_enable_display\fP (\fBssd1306_handle_t\fP handle)"
.br
.RI "Turns SSD1306 display panel on\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_disable_display\fP (\fBssd1306_handle_t\fP handle)"
.br
.RI "Turns SSD1306 display panel off (sleep mode)\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_pages\fP (\fBssd1306_handle_t\fP handle)"
.br
.RI "Displays segment data for each page supported by the SSD1306 display panel\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_pages\fP (\fBssd1306_handle_t\fP handle, uint8_t *buffer)"
.br
.RI "Sets segment data for each page supported by the SSD1306 display panel\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_get_pages\fP (\fBssd1306_handle_t\fP handle, uint8_t *buffer)"
.br
.RI "Gets segment data for each page supported by the SSD1306 display panel\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_pixel\fP (\fBssd1306_handle_t\fP handle, uint8_t xpos, uint8_t ypos, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a pixel\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_line\fP (\fBssd1306_handle_t\fP handle, uint8_t x0, uint8_t y0, uint8_t x1, uint8_t y1, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a line\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_circle\fP (\fBssd1306_handle_t\fP handle, uint8_t x0, uint8_t y0, uint8_t r, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a circle\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_circle\fP (\fBssd1306_handle_t\fP handle, uint8_t x0, uint8_t y0, uint8_t r, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a circle and display's the circle\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_filled_circle\fP (\fBssd1306_handle_t\fP handle, uint8_t x0, uint8_t y0, uint8_t r, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a filled circle and display's the filled circle\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_rectangle\fP (\fBssd1306_handle_t\fP handle, uint8_t x, uint8_t y, uint8_t w, uint8_t h, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a rectangle\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_rectangle\fP (\fBssd1306_handle_t\fP handle, uint8_t x, uint8_t y, uint8_t w, uint8_t h, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a rectangle and display's the rectangle\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_filled_rectangle\fP (\fBssd1306_handle_t\fP handle, uint8_t x, uint8_t y, uint8_t w, uint8_t h, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a filled rectangle and display's the filled rectangle\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_contrast\fP (\fBssd1306_handle_t\fP handle, uint8_t contrast)"
.br
.RI "Sets contrast of the SSD1306 display panel\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_bitmap\fP (\fBssd1306_handle_t\fP handle, uint8_t xpos, uint8_t ypos, const uint8_t *bitmap, uint8_t width, uint8_t height, bool invert)"
.br
.RI "Sets SSD1306 pages and segments data for a bitmap\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_bitmap\fP (\fBssd1306_handle_t\fP handle, uint8_t xpos, uint8_t ypos, const uint8_t *bitmap, uint8_t width, uint8_t height, bool invert)"
.br
.RI "Displays a bitmap on the SSD1306\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_image\fP (\fBssd1306_handle_t\fP handle, uint8_t page, uint8_t segment, const uint8_t *image, uint8_t width)"
.br
.RI "Displays an image by page and segment on the SSD1306\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_text\fP (\fBssd1306_handle_t\fP handle, uint8_t page, const char *text, bool invert)"
.br
.RI "Displays text by page on the SSD1306 with a maximum of 16-characters\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_text_x2\fP (\fBssd1306_handle_t\fP handle, uint8_t page, const char *text, bool invert)"
.br
.RI "Displays text x2 larger by page on the SSD1306\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_text_x3\fP (\fBssd1306_handle_t\fP handle, uint8_t page, const char *text, bool invert)"
.br
.RI "Displays text x3 larger by page on the SSD1306\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_textbox_banner\fP (\fBssd1306_handle_t\fP handle, uint8_t page, uint8_t segment, const char *text, uint8_t box_width, bool invert, uint8_t delay)"
.br
.RI "Displays scrolling text within a box as banner by page and segment on the SSD1306 with a maximum of 100-characters\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_textbox_ticker\fP (\fBssd1306_handle_t\fP handle, uint8_t page, uint8_t segment, const char *text, uint8_t box_width, bool invert, uint8_t delay)"
.br
.RI "Displays scrolling text within a box as a ticker by page and segment on the SSD1306 with a maximum of 100-characters\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_clear_display_page\fP (\fBssd1306_handle_t\fP handle, uint8_t page, bool invert)"
.br
.RI "Clears a page from the SSD1306 display\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_clear_display\fP (\fBssd1306_handle_t\fP handle, bool invert)"
.br
.RI "Clears the entire SSD1306 display\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_hardware_scroll\fP (\fBssd1306_handle_t\fP handle, \fBssd1306_scroll_types_t\fP scroll, \fBssd1306_scroll_frames_t\fP frame_frequency)"
.br
.RI "Sets SSD1306 scroll orientation and frame frequency for hardware based scrolling text\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_set_software_scroll\fP (\fBssd1306_handle_t\fP handle, uint8_t start, uint8_t end)"
.br
.RI "Sets SSD1306 start and end page for software based scrolling text\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_software_scroll_text\fP (\fBssd1306_handle_t\fP handle, const char *text, bool invert)"
.br
.RI "Displays software based scrolling text on the SSD1306\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_clear_display_software_scroll\fP (\fBssd1306_handle_t\fP handle)"
.br
.RI "Clears software based scrolling text from SSD1306 display\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_wrap_around\fP (\fBssd1306_handle_t\fP handle, \fBssd1306_scroll_types_t\fP scroll, uint8_t start, uint8_t end, int8_t delay)"
.br
.RI "Sets SSD1306 scroll orientation, start and end pages to wrap around the display\&. "
.ti -1c
.RI "uint8_t \fBssd1306_copy_bit\fP (uint8_t src, uint8_t src_bits, uint8_t dst, uint8_t dst_bits)"
.br
.RI "Copies bit from source to destination\&. "
.ti -1c
.RI "void \fBssd1306_invert_buffer\fP (uint8_t *buf, size_t blen)"
.br
.RI "Inverts the buffer data\&. "
.ti -1c
.RI "void \fBssd1306_flip_buffer\fP (uint8_t *buf, size_t blen)"
.br
.RI "Flips the buffer data (upsidedown)\&. "
.ti -1c
.RI "uint8_t \fBssd1306_rotate_byte\fP (uint8_t ch1)"
.br
.RI "Rotates 8-bits, as an example, 0x12 becomes 0x48\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_display_fadeout\fP (\fBssd1306_handle_t\fP handle)"
.br
.RI "SSD1306 display is faded out and cleared\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_init\fP (i2c_master_bus_handle_t master_handle, const \fBssd1306_config_t\fP *ssd1306_config, \fBssd1306_handle_t\fP *ssd1306_handle)"
.br
.RI "Initializes an SSD1306 device onto the I2C master bus\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_remove\fP (\fBssd1306_handle_t\fP handle)"
.br
.RI "Removes an SSD1306 device from master bus\&. "
.ti -1c
.RI "esp_err_t \fBssd1306_delete\fP (\fBssd1306_handle_t\fP handle)"
.br
.RI "Removes an SSD1306 device from master bus and frees handle\&. "
.ti -1c
.RI "const char * \fBssd1306_get_fw_version\fP (void)"
.br
.RI "Converts SSD1306 firmware version numbers (major, minor, patch) into a string\&. "
.ti -1c
.RI "int32_t \fBssd1306_get_fw_version_number\fP (void)"
.br
.RI "Converts SSD1306 firmware version numbers (major, minor, patch) into an integer value\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
