.TH "ssd1306_bdf_font_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssd1306_bdf_font_s \- SSD1306 BDF font structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ssd1306\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBencoding\fP"
.br
.ti -1c
.RI "uint8_t \fBwidth\fP"
.br
.ti -1c
.RI "uint8_t \fBbbw\fP"
.br
.ti -1c
.RI "uint8_t \fBbbh\fP"
.br
.ti -1c
.RI "uint8_t \fBbbx\fP"
.br
.ti -1c
.RI "uint8_t \fBbby\fP"
.br
.ti -1c
.RI "uint8_t \fBnum_data\fP"
.br
.ti -1c
.RI "uint8_t \fBy_start\fP"
.br
.ti -1c
.RI "uint8_t \fBy_end\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
SSD1306 BDF font structure definition\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
