.TH "ssd1306_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssd1306_context_t \- SSD1306 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ssd1306\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBssd1306_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "uint8_t \fBwidth\fP"
.br
.ti -1c
.RI "uint8_t \fBheight\fP"
.br
.ti -1c
.RI "bool \fBscroll_enabled\fP"
.br
.ti -1c
.RI "uint8_t \fBscroll_start\fP"
.br
.ti -1c
.RI "uint8_t \fBscroll_end\fP"
.br
.ti -1c
.RI "int8_t \fBscroll_direction\fP"
.br
.ti -1c
.RI "uint8_t \fBpages\fP"
.br
.ti -1c
.RI "\fBssd1306_page_t\fP \fBpage\fP [16]"
.br
.in -1c
.SH "Detailed Description"
.PP 
SSD1306 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBssd1306_config_t\fP dev_config"
ssd1306 device configuration 
.SS "uint8_t height"
ssd1306 height display panel 
.SS "i2c_master_dev_handle_t i2c_handle"
ssd1306 i2c device handle 
.SS "\fBssd1306_page_t\fP page[16]"
ssd1306 pages of segment data to display 
.SS "uint8_t pages"
ssd1306 number of pages supported by display panel 
.SS "int8_t scroll_direction"
ssd1306 scroll direction 
.SS "bool scroll_enabled"
ssd1306 scroll enabled when true 
.SS "uint8_t scroll_end"
ssd1306 end page of scroll 
.SS "uint8_t scroll_start"
ssd1306 start page of scroll 
.SS "uint8_t width"
ssd1306 width of display panel 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
