.TH "tbi2cxxx_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tbi2cxxx_context_t \- TBI2CXXX context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tbi2cxxx\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtbi2cxxx_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TBI2CXXX context structure\&. 
.SH "Field Documentation"
.PP 
.SS "i2c_master_dev_handle_t i2c_handle"
I2C device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
