.TH "components/peripherals/i2c/esp_tbi2cxxx/include/tbi2cxxx_version.h" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/i2c/esp_tbi2cxxx/include/tbi2cxxx_version.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTBI2CXXX_FW_VERSION_MAJOR\fP   1"
.br
.ti -1c
.RI "#define \fBTBI2CXXX_FW_VERSION_MINOR\fP   1"
.br
.ti -1c
.RI "#define \fBTBI2CXXX_FW_VERSION_PATCH\fP   6"
.br
.ti -1c
.RI "#define \fBSTR_QUOTES\fP(x)"
.br
.ti -1c
.RI "#define \fBSTR\fP(x)"
.br
.ti -1c
.RI "#define \fBTBI2CXXX_FW_VERSION_STR\fP"
.br
.ti -1c
.RI "#define \fBTBI2CXXX_FW_VERSION_PARAMS_INT32\fP(major,  minor,  patch)"
.br
.ti -1c
.RI "#define \fBTBI2CXXX_FW_VERSION_INT32\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
