.TH "components/peripherals/i2c/esp_tlv493d/tlv493d.c" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/i2c/esp_tlv493d/tlv493d.c
.SH SYNOPSIS
.br
.PP
\fR#include 'include/tlv493d\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include <esp_log\&.h>\fP
.br
\fR#include <esp_check\&.h>\fP
.br
\fR#include <esp_timer\&.h>\fP
.br
\fR#include <freertos/FreeRTOS\&.h>\fP
.br
\fR#include <freertos/task\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTLV493D_REG_BX_MSB_R\fP   UINT8_C(0x00)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_BY_MSB_R\fP   UINT8_C(0x01)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_BZ_MSB_R\fP   UINT8_C(0x02)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_TEMP_MSB_R\fP   UINT8_C(0x03)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_BX_BY_LSB_R\fP   UINT8_C(0x04)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_BZ_LSB_R\fP   UINT8_C(0x05)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_TEMP_LSB_R\fP   UINT8_C(0x06)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_FACTSET1_R\fP   UINT8_C(0x07)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_FACTSET2_R\fP   UINT8_C(0x08)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_FACTSET3_R\fP   UINT8_C(0x09)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_MOD1_W\fP   UINT8_C(0x01)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_RESERVED2_W\fP   UINT8_C(0x02)"
.br
.ti -1c
.RI "#define \fBTLV493D_REG_MOD2_W\fP   UINT8_C(0x03)"
.br
.ti -1c
.RI "#define \fBTLV493D_DATA_POLL_TIMEOUT_MS\fP   UINT16_C(1000)"
.br
.ti -1c
.RI "#define \fBTLV493D_DATA_READY_DELAY_MS\fP   UINT16_C(2)"
.br
.ti -1c
.RI "#define \fBTLV493D_POWERUP_DELAY_MS\fP   UINT16_C(120)"
.br
.ti -1c
.RI "#define \fBTLV493D_RESET_DELAY_MS\fP   UINT16_C(25)"
.br
.ti -1c
.RI "#define \fBTLV493D_SETUP_DELAY_MS\fP   UINT16_C(15)"
.br
.ti -1c
.RI "#define \fBTLV493D_APPSTART_DELAY_MS\fP   UINT16_C(25)"
.br
.ti -1c
.RI "#define \fBTLV493D_CMD_DELAY_MS\fP   UINT16_C(5)"
.br
.ti -1c
.RI "#define \fBTLV493D_TX_RX_DELAY_MS\fP   UINT16_C(10)"
.br
.ti -1c
.RI "#define \fBESP_TIMEOUT_CHECK\fP(start,  len)"
.br
.ti -1c
.RI "#define \fBESP_ARG_CHECK\fP(VAL)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fBtlv493d_init\fP (i2c_master_bus_handle_t master_handle, const \fBtlv493d_config_t\fP *tlv493d_config, \fBtlv493d_handle_t\fP *tlv493d_handle)"
.br
.RI "Initializes an TLV493D device onto the I2C master bus\&. "
.ti -1c
.RI "esp_err_t \fBtlv493d_get_data\fP (\fBtlv493d_handle_t\fP handle, \fBtlv493d_data_t\fP *const data)"
.br
.ti -1c
.RI "esp_err_t \fBtlv493d_get_data_status\fP (\fBtlv493d_handle_t\fP handle, bool *const ready)"
.br
.ti -1c
.RI "esp_err_t \fBtlv493d_remove\fP (\fBtlv493d_handle_t\fP handle)"
.br
.RI "Removes an TLV493D device from master bus\&. "
.ti -1c
.RI "esp_err_t \fBtlv493d_delete\fP (\fBtlv493d_handle_t\fP handle)"
.br
.RI "Removes an TLV493D device from master bus and frees handle\&. "
.in -1c
.SH "Detailed Description"
.PP 
ESP-IDF driver for TLV493D magnetic sensor

.PP
Ported from esp-open-rtos

.PP
Copyright (c) 2024 Eric Gionet (gionet.c.eric@gmail.com)

.PP
MIT Licensed as described in the file LICENSE 
.SH "Macro Definition Documentation"
.PP 
.SS "#define ESP_ARG_CHECK( VAL)"
\fBValue:\fP
.nf
do { if (!(VAL)) return ESP_ERR_INVALID_ARG; } while (0)
.PP
.fi

.SS "#define ESP_TIMEOUT_CHECK( start,  len)"
\fBValue:\fP
.nf
((uint64_t)(esp_timer_get_time() \- (start)) >= (len))
.PP
.fi

.SS "#define TLV493D_APPSTART_DELAY_MS   UINT16_C(25)"
delay after initialization before application start-up 
.SS "#define TLV493D_CMD_DELAY_MS   UINT16_C(5)"
delay before attempting I2C transactions after a command is issued 
.SS "#define TLV493D_TX_RX_DELAY_MS   UINT16_C(10)"
delay after attempting an I2C transmit transaction and attempting an I2C receive transaction 
.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
