.TH "components/peripherals/i2c/esp_tlv493d/include/tlv493d.h" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/peripherals/i2c/esp_tlv493d/include/tlv493d.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <stdbool\&.h>\fP
.br
\fR#include <esp_err\&.h>\fP
.br
\fR#include <driver/i2c_master\&.h>\fP
.br
\fR#include <type_utils\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtlv493d_raw_data_s\fP"
.br
.ti -1c
.RI "struct \fBtlv493d_data_s\fP"
.br
.ti -1c
.RI "struct \fBtlv493d_config_s\fP"
.br
.RI "TLV493D configuration structure\&. "
.ti -1c
.RI "struct \fBtlv493d_context_t\fP"
.br
.RI "TLV493D context structure\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2C_TLV493D_DEV_CLK_SPD\fP   UINT32_C(100000)"
.br
.RI "tlv493d I2C default clock frequency (100KHz) "
.ti -1c
.RI "#define \fBI2C_TLV493D_DEV_ADDR_LO\fP   UINT8_C(0x1F)"
.br
.RI "tlv493d I2C address "
.ti -1c
.RI "#define \fBI2C_TLV493D_DEV_ADDR_HI\fP   UINT8_C(0x5E)"
.br
.RI "tlv493d I2C address "
.ti -1c
.RI "#define \fBI2C_XFR_TIMEOUT_MS\fP   (500)"
.br
.RI "I2C transaction timeout in milliseconds\&. "
.ti -1c
.RI "#define \fBI2C_TLV493D_CONFIG_DEFAULT\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBtlv493d_power_modes_e\fP \fBtlv493d_power_modes_t\fP"
.br
.RI "TLV493D power modes enumerator\&. "
.ti -1c
.RI "typedef enum \fBtlv493d_channel_conversions_e\fP \fBtlv493d_channel_conversions_t\fP"
.br
.RI "TLV493D channel conversations enumerator\&. "
.ti -1c
.RI "typedef enum \fBtlv493d_i2c_addresses_e\fP \fBtlv493d_i2c_addresses_t\fP"
.br
.RI "TLV493D addresses for slaves enumerator\&. "
.ti -1c
.RI "typedef enum \fBtlv493d_low_power_periods_e\fP \fBtlv493d_low_power_periods_t\fP"
.br
.RI "TLV493D low power periods enumerator\&. "
.ti -1c
.RI "typedef struct \fBtlv493d_raw_data_s\fP \fBtlv493d_data_signal_t\fP"
.br
.ti -1c
.RI "typedef struct \fBtlv493d_data_s\fP \fBtlv493d_data_t\fP"
.br
.ti -1c
.RI "typedef struct \fBtlv493d_config_s\fP \fBtlv493d_config_t\fP"
.br
.RI "TLV493D configuration structure\&. "
.ti -1c
.RI "typedef struct tlv493d_context_t \fBtlv493d_context_t\fP"
.br
.RI "TLV493D context structure definition\&. "
.ti -1c
.RI "typedef struct \fBtlv493d_context_t\fP * \fBtlv493d_handle_t\fP"
.br
.RI "TLV493D handle structure definition\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtlv493d_power_modes_e\fP { \fBTLV493D_POWER_DOWN_MODE\fP, \fBTLV493D_FAST_MODE\fP, \fBTLV493D_LOW_POWER_MODE\fP, \fBTLV493D_ULTRA_LOW_POWER_MODE\fP, \fBTLV493D_MASTER_CONTROLLED_MODE\fP }"
.br
.RI "TLV493D power modes enumerator\&. "
.ti -1c
.RI "enum \fBtlv493d_channel_conversions_e\fP { \fBTLV493D_CHANNEL_CONV_COMPLETED\fP = (0b00), \fBTLV493D_CHANNEL_Y_CONV_ONGOING\fP = (0b01), \fBTLV493D_CHANNEL_Z_CONV_ONGOING\fP = (0b10), \fBTLV493D_CHANNEL_TEMP_CONV_ONGOING\fP = (0b11) }"
.br
.RI "TLV493D channel conversations enumerator\&. "
.ti -1c
.RI "enum \fBtlv493d_i2c_addresses_e\fP { \fBTLV493D_I2C_ADDRESS_00\fP = (0b00), \fBTLV493D_I2C_ADDRESS_01\fP = (0b01), \fBTLV493D_I2C_ADDRESS_10\fP = (0b10), \fBTLV493D_I2C_ADDRESS_11\fP = (0b11) }"
.br
.RI "TLV493D addresses for slaves enumerator\&. "
.ti -1c
.RI "enum \fBtlv493d_low_power_periods_e\fP { \fBTLV493D_LOW_POWER_PERIOD_100MS\fP = (0b0), \fBTLV493D_LOW_POWER_PERIOD_12MS\fP = (0b1) }"
.br
.RI "TLV493D low power periods enumerator\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "union \fB__attribute__\fP ((packed)) ahtxx_status_register_u"
.br
.RI "AHTXX status register structure definition\&. "
.ti -1c
.RI "esp_err_t \fBtlv493d_init\fP (i2c_master_bus_handle_t master_handle, const \fBtlv493d_config_t\fP *tlv493d_config, \fBtlv493d_handle_t\fP *tlv493d_handle)"
.br
.RI "Initializes an TLV493D device onto the I2C master bus\&. "
.ti -1c
.RI "esp_err_t \fBtlv493d_get_data\fP (\fBtlv493d_handle_t\fP handle, \fBtlv493d_data_t\fP *const data)"
.br
.ti -1c
.RI "esp_err_t \fBtlv493d_get_data_status\fP (\fBtlv493d_handle_t\fP handle, bool *const ready)"
.br
.ti -1c
.RI "esp_err_t \fBtlv493d_power_down\fP (\fBtlv493d_handle_t\fP handle)"
.br
.ti -1c
.RI "esp_err_t \fBtlv493d_power_up\fP (\fBtlv493d_handle_t\fP handle)"
.br
.ti -1c
.RI "esp_err_t \fBtlv493d_reset\fP (\fBtlv493d_handle_t\fP handle)"
.br
.RI "Issues soft-reset and initializes TLV493D\&. See datasheet for details\&. "
.ti -1c
.RI "esp_err_t \fBtlv493d_remove\fP (\fBtlv493d_handle_t\fP handle)"
.br
.RI "Removes an TLV493D device from master bus\&. "
.ti -1c
.RI "esp_err_t \fBtlv493d_delete\fP (\fBtlv493d_handle_t\fP handle)"
.br
.RI "Removes an TLV493D device from master bus and frees handle\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBtlv493d_temperature_msb_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_bx_by_lsb_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_bz_lsb_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_factory_setting1_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_factory_setting2_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_factory_setting3_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_reserved1_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_mode1_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_reserved2_register_t\fP"
.br
.ti -1c
.RI "\fBtlv493d_mode2_register_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
