.TH "tlv493d_data_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlv493d_data_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx_axis\fP"
.br
.ti -1c
.RI "float \fBy_axis\fP"
.br
.ti -1c
.RI "float \fBz_axis\fP"
.br
.ti -1c
.RI "float \fBtemperature\fP"
.br
.ti -1c
.RI "bool \fBtemperature_enabled\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float temperature"
temperature in degrees celsius 
.SS "float x_axis"
x-axis magnetic in mT (+/-130 mT) 
.SS "float y_axis"
y-axis magnetic in mT (+/-130 mT) 
.SS "float z_axis"
z-axis magnetic in mT (+/-130 mT) 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
