.TH "tlv493d_config_s" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlv493d_config_s \- TLV493D configuration structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlv493d\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBi2c_address\fP"
.br
.ti -1c
.RI "uint32_t \fBi2c_clock_speed\fP"
.br
.ti -1c
.RI "bool \fBparity_test_enabled\fP"
.br
.ti -1c
.RI "bool \fBtemperature_disabled\fP"
.br
.ti -1c
.RI "\fBtlv493d_power_modes_t\fP \fBpower_mode\fP"
.br
.ti -1c
.RI "bool \fBirq_pin_enabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TLV493D configuration structure\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t i2c_address"
tlv493d i2c device address 
.SS "uint32_t i2c_clock_speed"
tlv493d i2c device scl clock speed 
.SS "bool irq_pin_enabled"
tlv493d interrupt pin enabled when true 
.SS "bool parity_test_enabled"
tlv493d parity test enabled when true 
.SS "\fBtlv493d_power_modes_t\fP power_mode"
tlv493d power mode 
.SS "bool temperature_disabled"
tlv493d temperature sensor disabled when true 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
