.TH "tlv493d_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlv493d_context_t \- TLV493D context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlv493d\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBtlv493d_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.ti -1c
.RI "tlv493d_factory_setting1_register_t \fBfactory_setting1_reg\fP"
.br
.ti -1c
.RI "tlv493d_factory_setting2_register_t \fBfactory_setting2_reg\fP"
.br
.ti -1c
.RI "tlv493d_factory_setting3_register_t \fBfactory_setting3_reg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TLV493D context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBtlv493d_config_t\fP dev_config"
tlv493d device configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
tlv493d I2C device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
