.TH "vector_int16_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vector_int16_t \- Vector_int16 structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <vector_int16\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBx\fP"
.br
.ti -1c
.RI "int16_t \fBy\fP"
.br
.ti -1c
.RI "int16_t \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector_int16 structure\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
