.TH "components/utilities/esp_math3d/vector_int16.c" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
components/utilities/esp_math3d/vector_int16.c
.SH SYNOPSIS
.br
.PP
\fR#include 'vector_int16\&.h'\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <stdio\&.h>\fP
.br
\fR#include <esp_log\&.h>\fP
.br
\fR#include <esp_check\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBESP_ARG_CHECK\fP(VAL)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "esp_err_t \fBvector_int16_init\fP (\fBvector_int16_handle_t\fP *vector_int16_handle)"
.br
.ti -1c
.RI "esp_err_t \fBvector_int16_init_data\fP (\fBvector_int16_handle_t\fP vector_int16_handle, int16_t nx, int16_t ny, int16_t nz)"
.br
.ti -1c
.RI "esp_err_t \fBvector_int16_get_magnitude\fP (\fBvector_int16_handle_t\fP vector_int16_handle, float *magnitude)"
.br
.ti -1c
.RI "esp_err_t \fBvector_int16_normalize\fP (\fBvector_int16_handle_t\fP vector_int16_handle)"
.br
.ti -1c
.RI "esp_err_t \fBvector_int16_get_normalized\fP (\fBvector_int16_handle_t\fP vector_int16_handle, \fBvector_int16_handle_t\fP *normalized_handle)"
.br
.ti -1c
.RI "esp_err_t \fBvector_int16_rotate\fP (\fBvector_int16_handle_t\fP vector_int16_handle, \fBquaternion_handle_t\fP quaternion_handle)"
.br
.ti -1c
.RI "esp_err_t \fBvector_int16_get_rotated\fP (\fBvector_int16_handle_t\fP vector_int16_handle, \fBquaternion_handle_t\fP quaternion_handle, \fBvector_int16_handle_t\fP *rotated_handle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESP-IDF math 3d library

.PP
Ported from esp-open-rtos

.PP
Copyright (c) 2024 Eric Gionet (gionet.c.eric@gmail.com)

.PP
MIT Licensed as described in the file LICENSE 
.SH "Macro Definition Documentation"
.PP 
.SS "#define ESP_ARG_CHECK( VAL)"
\fBValue:\fP
.nf
do { if (!(VAL)) return ESP_ERR_INVALID_ARG; } while (0)
.PP
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
