.TH "veml6040_context_t" 3 "ESP-IDF Components by K0I05" \" -*- nroff -*-
.ad l
.nh
.SH NAME
veml6040_context_t \- VEML6040 context structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <veml6040\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBveml6040_config_t\fP \fBdev_config\fP"
.br
.ti -1c
.RI "i2c_master_dev_handle_t \fBi2c_handle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
VEML6040 context structure\&. 
.SH "Field Documentation"
.PP 
.SS "\fBveml6040_config_t\fP dev_config"
veml6040 device configuration 
.SS "i2c_master_dev_handle_t i2c_handle"
veml6040 i2c device handle 

.SH "Author"
.PP 
Generated automatically by Doxygen for ESP-IDF Components by K0I05 from the source code\&.
